# Generated by Django 4.1.6 on 2023-02-16 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('userEmailId', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=30)),
                ('lastName', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('DOB', models.DateField(max_length=10)),
                ('createdDate', models.DateField(max_length=10)),
                ('updatedDate', models.DateField(max_length=10)),
                ('phoneNumber', models.CharField(max_length=10, unique=True)),
                ('address', models.CharField(max_length=254, null=True)),
                ('image', models.ImageField(null=True, upload_to='')),
            ],
        ),
    ]
