# Generated by Django 4.1.6 on 2023-03-23 18:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cabName', models.CharField(max_length=30)),
                ('noOfSeats', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DOB', models.DateField(max_length=10)),
                ('updatedDate', models.DateField(max_length=10)),
                ('phoneNumber', models.CharField(max_length=10, unique=True)),
                ('address', models.CharField(max_length=254, null=True)),
                ('image', models.ImageField(null=True, upload_to='userProfilePicture')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('routeName', models.CharField(blank=True, max_length=30)),
                ('shift', models.CharField(blank=True, max_length=10)),
                ('timingDescription', models.CharField(blank=True, max_length=30)),
                ('routeDescription', models.CharField(blank=True, max_length=250)),
                ('cab', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='MasterApp.cab')),
            ],
        ),
        migrations.CreateModel(
            name='CabBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift', models.CharField(blank=True, max_length=10)),
                ('isCancelled', models.BooleanField(blank=True, default=False)),
                ('isCompleted', models.BooleanField(blank=True, default=False)),
                ('bookedDate', models.DateField(blank=True)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MasterApp.route')),
                ('userRe', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
