# Generated by Django 4.1.6 on 2023-02-19 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MasterApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userRole', models.CharField(max_length=1, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='userEmailId',
            field=models.EmailField(max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='user',
            name='userRole',
            field=models.ForeignKey(default=2, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='MasterApp.userrole', to_field='userRole'),
        ),
    ]
