# Generated by Django 4.1.6 on 2023-02-27 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MasterApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistration',
            name='userRole',
            field=models.ForeignKey(default='E', on_delete=django.db.models.deletion.DO_NOTHING, to='MasterApp.userrole', to_field='userRole'),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='userRole',
            field=models.CharField(default='E', max_length=1, unique=True),
        ),
    ]
