# Generated by Django 4.1.6 on 2023-03-20 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MasterApp', '0002_cab'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('routeName', models.CharField(blank=True, max_length=30)),
                ('shift', models.CharField(blank=True, max_length=10)),
                ('timingDescription', models.CharField(blank=True, max_length=30)),
                ('routeDescription', models.CharField(blank=True, max_length=250)),
                ('cab', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='MasterApp.cab')),
            ],
        ),
    ]
